"""create listings

Revision ID: 0001
Revises:
Create Date: 2026-09-24 13:20:44.806341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('type', sa.Enum('rent', 'sale', 'shortlet', name='listing_type'), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bedrooms >= 0', name='ck_listings_bedrooms_nonneg'),
    sa.CheckConstraint('price > 0', name='ck_listings_price_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_agent_id'), 'listings', ['agent_id'], unique=False)
    op.create_index(op.f('ix_listings_bedrooms'), 'listings', ['bedrooms'], unique=False)
    op.create_index('ix_listings_type_price', 'listings', ['type', 'price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_listings_type_price', table_name='listings')
    op.drop_index(op.f('ix_listings_bedrooms'), table_name='listings')
    op.drop_index(op.f('ix_listings_agent_id'), table_name='listings')
    op.drop_table('listings')
    sa.Enum(name='listing_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
