"""create listings table

Revision ID: 4b6245c8171e
Revises:
Create Date: 2026-09-24 12:00:17.820340

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "4b6245c8171e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "type",
            sa.Enum("rent", "sale", "shortlet", name="listing_type"),
            nullable=False,
        ),
        sa.Column("bedrooms", sa.Integer(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("bedrooms >= 0", name="ck_listings_bedrooms_nonneg"),
        sa.CheckConstraint("price > 0", name="ck_listings_price_positive"),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.create_index('idx_listings_location', 'listings', ['location'], unique=False, postgresql_using='gist')
    op.create_index(
        op.f("ix_listings_agent_id"), "listings", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_listings_bedrooms"), "listings", ["bedrooms"], unique=False
    )
    op.create_index(
        "ix_listings_type_price", "listings", ["type", "price"], unique=False
    )
    op.drop_index(
        op.f("secondary_unit_lookup_abbrev_idx"), table_name="secondary_unit_lookup"
    )
    op.drop_index(op.f("county_lookup_name_idx"), table_name="county_lookup")
    op.drop_index(op.f("county_lookup_state_idx"), table_name="county_lookup")
    op.drop_index(op.f("countysub_lookup_name_idx"), table_name="countysub_lookup")
    op.drop_index(op.f("countysub_lookup_state_idx"), table_name="countysub_lookup")
    op.drop_index(op.f("idx_tiger_county"), table_name="county")

    op.drop_index(op.f("idx_tiger_featnames_lname"), table_name="featnames")
    op.drop_index(op.f("idx_tiger_featnames_snd_name"), table_name="featnames")
    op.drop_index(op.f("idx_tiger_featnames_tlid_statefp"), table_name="featnames")

    op.drop_index(
        op.f("idx_tiger_state_the_geom_gist"),
        table_name="state",
        postgresql_using="gist",
    )

    op.drop_index(
        op.f("street_type_lookup_abbrev_idx"), table_name="street_type_lookup"
    )

    op.drop_index(
        op.f("idx_addrfeat_geom_gist"), table_name="addrfeat", postgresql_using="gist"
    )
    op.drop_index(op.f("idx_addrfeat_tlid"), table_name="addrfeat")
    op.drop_index(op.f("idx_addrfeat_zipl"), table_name="addrfeat")
    op.drop_index(op.f("idx_addrfeat_zipr"), table_name="addrfeat")

    op.drop_index(op.f("idx_edges_tlid"), table_name="edges")
    op.drop_index(op.f("idx_tiger_edges_countyfp"), table_name="edges")
    op.drop_index(
        op.f("idx_tiger_edges_the_geom_gist"),
        table_name="edges",
        postgresql_using="gist",
    )

    op.drop_index(op.f("place_lookup_name_idx"), table_name="place_lookup")
    op.drop_index(op.f("place_lookup_state_idx"), table_name="place_lookup")

    op.drop_index(
        op.f("tige_cousub_the_geom_gist"), table_name="cousub", postgresql_using="gist"
    )

    op.drop_index(
        op.f("tiger_place_the_geom_gist"), table_name="place", postgresql_using="gist"
    )

    op.drop_index(op.f("idx_tiger_faces_countyfp"), table_name="faces")
    op.drop_index(op.f("idx_tiger_faces_tfid"), table_name="faces")
    op.drop_index(
        op.f("tiger_faces_the_geom_gist"), table_name="faces", postgresql_using="gist"
    )

    op.drop_index(op.f("idx_tiger_addr_tlid_statefp"), table_name="addr")
    op.drop_index(op.f("idx_tiger_addr_zip"), table_name="addr")

    op.drop_index(op.f("direction_lookup_abbrev_idx"), table_name="direction_lookup")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_index(
        op.f("direction_lookup_abbrev_idx"),
        "direction_lookup",
        ["abbrev"],
        unique=False,
    )

    op.create_index(op.f("idx_tiger_addr_zip"), "addr", ["zip"], unique=False)
    op.create_index(
        op.f("idx_tiger_addr_tlid_statefp"), "addr", ["tlid", "statefp"], unique=False
    )

    op.create_index(
        op.f("tiger_faces_the_geom_gist"),
        "faces",
        ["the_geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(op.f("idx_tiger_faces_tfid"), "faces", ["tfid"], unique=False)
    op.create_index(
        op.f("idx_tiger_faces_countyfp"), "faces", ["countyfp"], unique=False
    )

    op.create_index(
        op.f("tiger_place_the_geom_gist"),
        "place",
        ["the_geom"],
        unique=False,
        postgresql_using="gist",
    )

    op.create_index(
        op.f("tige_cousub_the_geom_gist"),
        "cousub",
        ["the_geom"],
        unique=False,
        postgresql_using="gist",
    )

    op.create_index(
        op.f("place_lookup_state_idx"), "place_lookup", ["state"], unique=False
    )
    op.create_index(
        op.f("place_lookup_name_idx"),
        "place_lookup",
        [sa.literal_column("soundex(name::text)")],
        unique=False,
    )

    op.create_index(
        op.f("idx_tiger_edges_the_geom_gist"),
        "edges",
        ["the_geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("idx_tiger_edges_countyfp"), "edges", ["countyfp"], unique=False
    )
    op.create_index(op.f("idx_edges_tlid"), "edges", ["tlid"], unique=False)

    op.create_index(op.f("idx_addrfeat_zipr"), "addrfeat", ["zipr"], unique=False)
    op.create_index(op.f("idx_addrfeat_zipl"), "addrfeat", ["zipl"], unique=False)
    op.create_index(op.f("idx_addrfeat_tlid"), "addrfeat", ["tlid"], unique=False)
    op.create_index(
        op.f("idx_addrfeat_geom_gist"),
        "addrfeat",
        ["the_geom"],
        unique=False,
        postgresql_using="gist",
    )

    op.create_index(
        op.f("street_type_lookup_abbrev_idx"),
        "street_type_lookup",
        ["abbrev"],
        unique=False,
    )

    op.create_index(
        op.f("idx_tiger_state_the_geom_gist"),
        "state",
        ["the_geom"],
        unique=False,
        postgresql_using="gist",
    )

    op.create_index(
        op.f("idx_tiger_featnames_tlid_statefp"),
        "featnames",
        ["tlid", "statefp"],
        unique=False,
    )
    op.create_index(
        op.f("idx_tiger_featnames_snd_name"),
        "featnames",
        [sa.literal_column("soundex(name::text)")],
        unique=False,
    )
    op.create_index(
        op.f("idx_tiger_featnames_lname"),
        "featnames",
        [sa.literal_column("lower(name::text)")],
        unique=False,
    )

    op.create_index(op.f("idx_tiger_county"), "county", ["countyfp"], unique=False)

    op.create_index(
        op.f("countysub_lookup_state_idx"), "countysub_lookup", ["state"], unique=False
    )
    op.create_index(
        op.f("countysub_lookup_name_idx"),
        "countysub_lookup",
        [sa.literal_column("soundex(name::text)")],
        unique=False,
    )

    op.create_index(
        op.f("county_lookup_state_idx"), "county_lookup", ["state"], unique=False
    )
    op.create_index(
        op.f("county_lookup_name_idx"),
        "county_lookup",
        [sa.literal_column("soundex(name::text)")],
        unique=False,
    )

    op.create_index(
        op.f("secondary_unit_lookup_abbrev_idx"),
        "secondary_unit_lookup",
        ["abbrev"],
        unique=False,
    )
    op.drop_index("ix_listings_type_price", table_name="listings")
    op.drop_index(op.f("ix_listings_bedrooms"), table_name="listings")
    op.drop_index(op.f("ix_listings_agent_id"), table_name="listings")
    op.drop_index(
        "idx_listings_location", table_name="listings", postgresql_using="gist"
    )
    op.drop_table("listings")
    # ### end Alembic commands ###
